name: Build and Deploy Docker Image on Dev

on:
  push:
    branches:
      - dev-integrate

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Create $ENTITY_API_VERSION
        run: |
          export ENTITY_API_VERSION=$(tr -d "\n\r" < ../VERSION | xargs)
          echo "ENTITY_API_VERSION: $ENTITY_API_VERSION" >> $ENTITY_API_VERSION

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make build script executable
        run: chmod +x ./docker-development.sh
        working-directory: ./docker

      - name: Run the Docker build shell script
        run: ./docker-development.sh build
        working-directory: ./docker

      - name: Tag the Docker Image
        run: docker image tag sennet/entity-api:${ENTITY_API_VERSION} sennet/entity-api-dev:latest
        working-directory: ./docker

      - name: Push the Docker image
        run: docker push sennet/entity-api-dev:latest
        working-directory: ./docker
